### ISSUE TITLE
Why was this so hard to find, am I missing something? Are there better alternatives?

### ISSUE THREAD

**Issue by GrayStrider** [ike18t/ts-mockery#21]
I just wanted to make a to-do implementation for TDD, and it took me like 30m to find decent mocking solution?..
![image](https://user-images.githubusercontent.com/43771776/68107097-c7b01280-ff37-11e9-9b75-1d4b74153736.png)

**Comment by ike18t** [comment]
For the scenario you have provided you don't even need mockery.

```typescript
tasks(): Promise<Task[]> {
  return Promise.resolve([]); // no need for mockery in this instance
}
```

It is hard for me to gather complete context from the screenshot but if what you provided is an attempt to mock a function on an object then you could do something like:
```typescript
Mock.of<TaskGetter>({ tasks: () => Promise.resolve([]) })
```
